import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-600 mb-8">
        Bedtime Genie · Last updated: May 2026 · Effective: May 2026
      </p>

      <div className="prose prose-sm max-w-none">
        <p className="text-gray-700 mb-8">
          Please read these Terms of Service ("Terms") carefully before using Bedtime Genie
          ("the App"). By downloading or using the App you agree to be bound by these Terms.
          If you do not agree, do not use the App.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          1. About the App
        </h2>
        <p className="text-gray-700 mb-6">
          Bedtime Genie is an AI-powered mobile app that generates personalised bedtime stories for
          children. It is developed and operated by an individual developer based in Australia.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          2. Eligibility
        </h2>
        <p className="text-gray-700 mb-6">
          The App is intended for use by parents, guardians, and carers aged 18 or older. By creating an
          account you confirm that you are at least 18 years old. The App is not intended to be used
          directly by children. Adults are responsible for supervising children's use of the App and the
          content it generates.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          3. Account
        </h2>
        <p className="text-gray-700 mb-4">
          You may sign in using Google, Apple, email and password, or continue as a guest. You are
          responsible for maintaining the security of your account and for all activity that occurs under
          it. Please notify us at{" "}
          <a href="mailto:bedtimegenie@gmail.com" className="text-blue-600 hover:text-blue-700">
            bedtimegenie@gmail.com
          </a>{" "}
          immediately if you suspect any unauthorised access.
        </p>
        <p className="text-gray-700 mb-6">
          Guest accounts are anonymous and tied to the device. Story libraries created as a guest cannot
          be transferred to a new device or recovered if the app is uninstalled.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          4. Free Plan and Premium Subscription
        </h2>

        <h3 className="font-semibold text-gray-900 mt-6 mb-3">Free plan</h3>
        <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
          <li>Generate unlimited stories</li>
          <li>Save up to 5 stories to your library</li>
          <li>1 child profile</li>
          <li>5 free AI narrations</li>
          <li>Up to 2 story series</li>
          <li>Sleep timer in the Sounds tab</li>
          <li>No screen dimming or offline downloads</li>
        </ul>

        <h3 className="font-semibold text-gray-900 mt-6 mb-3">Premium plan</h3>
        <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
          <li>Unlimited story saves</li>
          <li>Up to 6 child profiles</li>
          <li>Unlimited AI narration in 3 voices</li>
          <li>Unlimited story series</li>
          <li>Screen dimming during reading</li>
          <li>Offline story downloads</li>
          <li>Available as monthly or annual subscription</li>
        </ul>

        <h3 className="font-semibold text-gray-900 mt-6 mb-3">Billing</h3>
        <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
          <li>Subscriptions are billed through the Apple App Store or Google Play Store.</li>
          <li>Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date.</li>
          <li>You can manage or cancel your subscription in your device's App Store / Play Store settings.</li>
          <li>Refunds are subject to Apple's or Google's refund policies.</li>
        </ul>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          5. AI-Generated Content
        </h2>
        <p className="text-gray-700 mb-4">
          Stories, illustrations, and narration audio are generated by artificial intelligence
          (Groq / Llama model for story text, Together AI for illustrations, and Gemini for narration).
          By using the App you acknowledge that:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
          <li>AI-generated content may occasionally be imperfect, repetitive, or unexpected.</li>
          <li>We do not guarantee the accuracy, suitability, or educational value of generated content.</li>
          <li>You are responsible for reviewing stories before sharing them with your children.</li>
        </ul>
        <p className="text-gray-700 mb-6">
          Stories generated through the App are for your personal, non-commercial use. You may share
          individual stories with family and friends but may not resell or commercially exploit them.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          6. Acceptable Use
        </h2>
        <p className="text-gray-700 mb-4">You agree not to:</p>
        <ul className="list-disc list-inside text-gray-700 mb-6 space-y-2">
          <li>Use the App to generate content that is harmful, offensive, or inappropriate for children</li>
          <li>Attempt to reverse-engineer, copy, or reproduce the App or its AI prompts</li>
          <li>Use automated scripts or bots to generate stories at scale</li>
          <li>Circumvent subscription paywalls or attempt to fraudulently obtain Premium features</li>
          <li>Use the App for any unlawful purpose</li>
        </ul>
        <p className="text-gray-700 mb-6">
          We reserve the right to suspend or terminate accounts that violate these terms.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          7. Intellectual Property
        </h2>
        <p className="text-gray-700 mb-4">
          The App, its design, branding, and underlying code are owned by the developer and protected by
          copyright law. You may not copy, modify, or distribute any part of the App without written
          permission.
        </p>
        <p className="text-gray-700 mb-6">
          Stories generated for you through the App are provided for your personal use. We do not claim
          ownership of the specific story content generated for your account.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          8. Disclaimer of Warranties
        </h2>
        <p className="text-gray-700 mb-6">
          The App is provided "as is" and "as available" without warranties of any kind, express or
          implied. We do not warrant that the App will be uninterrupted, error-free, or that AI-generated
          content will always meet your expectations. Use of AI-generated content is at your own
          discretion.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          9. Limitation of Liability
        </h2>
        <p className="text-gray-700 mb-4">
          To the maximum extent permitted by Australian law, we shall not be liable for any indirect,
          incidental, special, or consequential damages arising from your use of the App, including but
          not limited to loss of data, loss of stories, or service interruptions.
        </p>
        <p className="text-gray-700 mb-6">
          Our total liability to you for any claim shall not exceed the amount you paid for the App in
          the 12 months preceding the claim.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          10. Changes to the App and Terms
        </h2>
        <p className="text-gray-700 mb-4">
          We may update these Terms from time to time. We will notify users of material changes by
          updating the "Last updated" date on this page. Continued use of the App after changes
          constitutes acceptance of the revised Terms.
        </p>
        <p className="text-gray-700 mb-6">
          We may modify, suspend, or discontinue features of the App at any time. We will endeavour to
          provide reasonable notice of significant changes.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          11. Governing Law
        </h2>
        <p className="text-gray-700 mb-6">
          These Terms are governed by the laws of Australia. Any disputes arising under these Terms
          will be subject to the exclusive jurisdiction of the courts of Australia.
        </p>

        <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">
          12. Contact Us
        </h2>
        <p className="text-gray-700 mb-4">
          If you have any questions about these Terms, please contact:
        </p>
        <p className="text-gray-700 mb-8">
          <strong>Bedtime Genie</strong>
          <br />
          Email:{" "}
          <a href="mailto:bedtimegenie@gmail.com" className="text-blue-600 hover:text-blue-700">
            bedtimegenie@gmail.com
          </a>
          <br />
          Location: Australia
        </p>

        <div className="text-center text-sm text-gray-600 pt-6 border-t border-gray-200 mt-12">
          <p>&copy; 2026 Bedtime Genie</p>
          <div className="mt-4 space-x-6">
            <Link href="/bedtimegenie/privacy-policy" className="text-blue-600 hover:text-blue-700">
              Privacy Policy
            </Link>
            <span className="text-gray-400">·</span>
            <a href="mailto:bedtimegenie@gmail.com" className="text-blue-600 hover:text-blue-700">
              Contact
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
